"""item_master

Revision ID: 0ad76a5775aa
Revises: 4454f91f3acd
Create Date: 2025-06-30 06:52:01.228420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad76a5775aa'
down_revision: Union[str, Sequence[str], None] = '4454f91f3acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_master_company_id'), table_name='company_master')
    op.drop_index(op.f('ix_company_master_company_name'), table_name='company_master')
    op.drop_table('company_master')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_master',
    sa.Column('company_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('business_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('company_id', name=op.f('company_master_pkey'))
    )
    op.create_index(op.f('ix_company_master_company_name'), 'company_master', ['company_name'], unique=False)
    op.create_index(op.f('ix_company_master_company_id'), 'company_master', ['company_id'], unique=False)
    # ### end Alembic commands ###
