"""tenders updated 2

Revision ID: 6c47e5cca6be
Revises: d1b1d074b0ef
Create Date: 2025-06-30 07:48:16.065637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c47e5cca6be'
down_revision: Union[str, Sequence[str], None] = 'd1b1d074b0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('tender_id', sa.String(length=50), nullable=False))
    op.alter_column('tenders', 'tender_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_tenders_tender_id'), 'tenders', ['tender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenders_tender_id'), table_name='tenders')
    op.alter_column('tenders', 'tender_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('tenders', 'tender_id')
    # ### end Alembic commands ###
