"""initial schema

Revision ID: 7a9999d321a2
Revises: 
Create Date: 2025-07-01 14:42:44.263004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9999d321a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_master',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_company_master_company_id'), 'company_master', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_master_company_name'), 'company_master', ['company_name'], unique=False)
    op.create_table('counter_guarantees',
    sa.Column('cg_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guarantee_type', sa.Enum('TBG', 'PBG', 'MPG', name='guarantee_type_enum'), nullable=False),
    sa.Column('guarantee_ref_number', sa.String(length=100), nullable=False),
    sa.Column('cg_date', sa.Date(), nullable=False),
    sa.Column('issuing_bank', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('release_date_bank', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('pending_status', sa.Enum('NOT_ISSUED', 'ISSUED_EXTENDED', 'EXTENSION_REQUIRED', 'NOT_RELEASED', 'RELEASED', name='cg_pending_status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('cg_id')
    )
    op.create_index(op.f('ix_counter_guarantees_cg_id'), 'counter_guarantees', ['cg_id'], unique=False)
    op.create_index(op.f('ix_counter_guarantees_guarantee_ref_number'), 'counter_guarantees', ['guarantee_ref_number'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('start_dt', sa.DateTime(), nullable=False),
    sa.Column('end_dt', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_description'), 'events', ['description'], unique=False)
    op.create_index(op.f('ix_events_end_dt'), 'events', ['end_dt'], unique=False)
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=False)
    op.create_index(op.f('ix_events_start_dt'), 'events', ['start_dt'], unique=False)
    op.create_table('tenders',
    sa.Column('tender_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tender_no', sa.String(length=50), nullable=False),
    sa.Column('tender_description', sa.Text(), nullable=False),
    sa.Column('tender_date', sa.Date(), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('tender_fees', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bond_guarantee_amt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('tender_id')
    )
    op.create_index(op.f('ix_tenders_tender_id'), 'tenders', ['tender_id'], unique=False)
    op.create_index(op.f('ix_tenders_tender_no'), 'tenders', ['tender_no'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('order_details',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('order_description', sa.String(length=500), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('order_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('AED', 'EUR', 'USD', name='currencyenum'), nullable=False),
    sa.Column('order_value_aed', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('revised_value_lme', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('revised_value_lme_aed', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('order_confirmation_no', sa.String(length=100), nullable=True),
    sa.Column('order_confirmation_date', sa.Date(), nullable=True),
    sa.Column('po_confirmation_date_srm', sa.Date(), nullable=True),
    sa.Column('drawing_submission_date', sa.Date(), nullable=True),
    sa.Column('drawing_approval_date', sa.Date(), nullable=True),
    sa.Column('last_contractual_delivery', sa.Date(), nullable=True),
    sa.Column('actual_last_delivery', sa.Date(), nullable=True),
    sa.Column('old_po_id', sa.Integer(), nullable=True),
    sa.Column('kka_commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('no_of_consignments', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_master.company_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['old_po_id'], ['order_details.order_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.tender_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_details_company_id'), 'order_details', ['company_id'], unique=False)
    op.create_index(op.f('ix_order_details_old_po_id'), 'order_details', ['old_po_id'], unique=False)
    op.create_index(op.f('ix_order_details_order_id'), 'order_details', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_details_po_number'), 'order_details', ['po_number'], unique=True)
    op.create_index(op.f('ix_order_details_tender_id'), 'order_details', ['tender_id'], unique=False)
    op.create_table('product_master',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_master.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_product_master_company_id'), 'product_master', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_master_product_id'), 'product_master', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_master_product_name'), 'product_master', ['product_name'], unique=False)
    op.create_table('tendering_companies',
    sa.Column('tendering_companies_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tender_no', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('tender_receipt_no', sa.String(length=100), nullable=True),
    sa.Column('tbg_no', sa.String(length=100), nullable=True),
    sa.Column('tbg_issuing_bank', sa.String(length=100), nullable=True),
    sa.Column('tender_deposit_receipt_no', sa.String(length=100), nullable=True),
    sa.Column('cheque_no', sa.String(length=50), nullable=True),
    sa.Column('tt_ref', sa.String(length=100), nullable=True),
    sa.Column('tt_date', sa.Date(), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('tbg_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tbg_expiry_date', sa.Date(), nullable=True),
    sa.Column('tbg_submitted_date', sa.Date(), nullable=True),
    sa.Column('tbg_release_date_dewa', sa.Date(), nullable=True),
    sa.Column('tbg_release_date_bank', sa.Date(), nullable=True),
    sa.Column('tender_extension_dates', sa.ARRAY(sa.Date()), nullable=True),
    sa.Column('tendering_currency', sa.Enum('AED', 'EUR', 'USD', name='currencyenum'), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('pending_status', sa.Enum('TO_BE_RELEASED', 'IN_EFFECT', 'RELEASED', name='pendingstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_master.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.tender_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_no'], ['tenders.tender_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tendering_companies_id')
    )
    op.create_index(op.f('ix_tendering_companies_company_id'), 'tendering_companies', ['company_id'], unique=False)
    op.create_index(op.f('ix_tendering_companies_tender_id'), 'tendering_companies', ['tender_id'], unique=False)
    op.create_index(op.f('ix_tendering_companies_tender_no'), 'tendering_companies', ['tender_no'], unique=True)
    op.create_index(op.f('ix_tendering_companies_tendering_companies_id'), 'tendering_companies', ['tendering_companies_id'], unique=False)
    op.create_table('item_master',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=False),
    sa.Column('hs_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product_master.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_item_master_hs_code'), 'item_master', ['hs_code'], unique=False)
    op.create_index(op.f('ix_item_master_item_id'), 'item_master', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_master_product_id'), 'item_master', ['product_id'], unique=False)
    op.create_table('material_performance_guarantees',
    sa.Column('mpg_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('mpg_no', sa.String(length=100), nullable=False),
    sa.Column('mpg_issuing_bank', sa.String(length=100), nullable=True),
    sa.Column('mpg_deposit_receipt_no', sa.String(length=100), nullable=True),
    sa.Column('cheque_no', sa.String(length=50), nullable=True),
    sa.Column('tt_date', sa.Date(), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('mpg_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mpg_expiry_date', sa.Date(), nullable=False),
    sa.Column('mpg_submitted_date', sa.Date(), nullable=True),
    sa.Column('mpg_return_date', sa.Date(), nullable=True),
    sa.Column('mpg_release_date_dewa', sa.Date(), nullable=True),
    sa.Column('mpg_release_date_bank', sa.Date(), nullable=True),
    sa.Column('mpg_extension_dates', sa.ARRAY(sa.Date()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('pending_status', sa.Enum('NOT_ISSUED', 'ISSUED_EXTENDED', 'EXTENSION_REQUIRED', 'NOT_RELEASED', 'RELEASED', name='mpg_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_details.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mpg_id')
    )
    op.create_index(op.f('ix_material_performance_guarantees_mpg_id'), 'material_performance_guarantees', ['mpg_id'], unique=False)
    op.create_index(op.f('ix_material_performance_guarantees_mpg_no'), 'material_performance_guarantees', ['mpg_no'], unique=False)
    op.create_index(op.f('ix_material_performance_guarantees_order_id'), 'material_performance_guarantees', ['order_id'], unique=False)
    op.create_table('order_events',
    sa.Column('order_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order_details.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_event_id')
    )
    op.create_index(op.f('ix_order_events_event_date'), 'order_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_order_events_order_event_id'), 'order_events', ['order_event_id'], unique=False)
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.create_table('performance_guarantees',
    sa.Column('pg_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('pg_no', sa.String(length=100), nullable=False),
    sa.Column('pg_issuing_bank', sa.String(length=100), nullable=True),
    sa.Column('pg_deposit_receipt_no', sa.String(length=100), nullable=True),
    sa.Column('cheque_no', sa.String(length=50), nullable=True),
    sa.Column('tt_date', sa.Date(), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('pg_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pg_expiry_date', sa.Date(), nullable=False),
    sa.Column('pg_submitted_date', sa.Date(), nullable=True),
    sa.Column('pg_return_date', sa.Date(), nullable=True),
    sa.Column('pg_release_date_dewa', sa.Date(), nullable=True),
    sa.Column('pg_release_date_bank', sa.Date(), nullable=True),
    sa.Column('pg_extension_dates', sa.ARRAY(sa.Date()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('pending_status', sa.Enum('NOT_ISSUED', 'ISSUED_EXTENDED', 'EXTENSION_REQUIRED', 'NOT_RELEASED', 'RELEASED', name='pbg_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_details.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pg_id')
    )
    op.create_index(op.f('ix_performance_guarantees_order_id'), 'performance_guarantees', ['order_id'], unique=False)
    op.create_index(op.f('ix_performance_guarantees_pg_id'), 'performance_guarantees', ['pg_id'], unique=False)
    op.create_index(op.f('ix_performance_guarantees_pg_no'), 'performance_guarantees', ['pg_no'], unique=False)
    op.create_table('post_tender_clarifications',
    sa.Column('ptc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tendering_companies_id', sa.Integer(), nullable=False),
    sa.Column('ptc_no', sa.Integer(), nullable=False),
    sa.Column('ptc_ref_no', sa.String(length=100), nullable=False),
    sa.Column('ptc_date', sa.Date(), nullable=False),
    sa.Column('ptc_received_date', sa.Date(), nullable=False),
    sa.Column('ptc_reply_required_by', sa.Date(), nullable=False),
    sa.Column('ptc_reply_submission_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['tendering_companies_id'], ['tendering_companies.tendering_companies_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ptc_id')
    )
    op.create_index(op.f('ix_post_tender_clarifications_ptc_id'), 'post_tender_clarifications', ['ptc_id'], unique=False)
    op.create_index(op.f('ix_post_tender_clarifications_tendering_companies_id'), 'post_tender_clarifications', ['tendering_companies_id'], unique=False)
    op.create_table('pre_tender_clarifications',
    sa.Column('pre_ptc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tendering_companies_id', sa.Integer(), nullable=False),
    sa.Column('pre_ptc_no', sa.Integer(), nullable=False),
    sa.Column('pre_ptc_ref_no', sa.String(length=100), nullable=False),
    sa.Column('pre_ptc_date', sa.Date(), nullable=False),
    sa.Column('pre_ptc_received_date', sa.Date(), nullable=False),
    sa.Column('pre_ptc_reply_required_by', sa.Date(), nullable=False),
    sa.Column('pre_ptc_reply_submission_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['tendering_companies_id'], ['tendering_companies.tendering_companies_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pre_ptc_id')
    )
    op.create_index(op.f('ix_pre_tender_clarifications_pre_ptc_id'), 'pre_tender_clarifications', ['pre_ptc_id'], unique=False)
    op.create_index(op.f('ix_pre_tender_clarifications_tendering_companies_id'), 'pre_tender_clarifications', ['tendering_companies_id'], unique=False)
    op.create_table('tender_company_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tendering_companies_id', sa.Integer(), nullable=False),
    sa.Column('item_no_dewa', sa.String(length=100), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['tendering_companies_id'], ['tendering_companies.tendering_companies_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_company_items_id'), 'tender_company_items', ['id'], unique=False)
    op.create_index(op.f('ix_tender_company_items_item_no_dewa'), 'tender_company_items', ['item_no_dewa'], unique=False)
    op.create_index(op.f('ix_tender_company_items_tendering_companies_id'), 'tender_company_items', ['tendering_companies_id'], unique=False)
    op.create_table('order_item_details',
    sa.Column('order_item_detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_description', sa.String(length=500), nullable=True),
    sa.Column('item_no_dewa', sa.String(length=100), nullable=False),
    sa.Column('item_quantity', sa.Integer(), nullable=False),
    sa.Column('item_unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('number_of_lots', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['order_details.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_item_detail_id')
    )
    op.create_index(op.f('ix_order_item_details_item_id'), 'order_item_details', ['item_id'], unique=False)
    op.create_index(op.f('ix_order_item_details_order_id'), 'order_item_details', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_item_details_order_item_detail_id'), 'order_item_details', ['order_item_detail_id'], unique=False)
    op.create_table('lot_monitoring',
    sa.Column('lot_id', sa.String(length=20), nullable=False),
    sa.Column('order_item_detail_id', sa.Integer(), nullable=False),
    sa.Column('shipment_no', sa.String(length=50), nullable=True),
    sa.Column('item_lot_no', sa.String(length=50), nullable=True),
    sa.Column('item_unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('item_total_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('contractual_delivery_date', sa.Date(), nullable=True),
    sa.Column('inspection_call_date_tent', sa.Date(), nullable=True),
    sa.Column('inspection_call_date_act', sa.Date(), nullable=True),
    sa.Column('inspection_date_advised', sa.Date(), nullable=True),
    sa.Column('no_of_inspection_days', sa.Integer(), nullable=True),
    sa.Column('actual_inspection_date', sa.Date(), nullable=True),
    sa.Column('inspection_delay_days', sa.Integer(), nullable=True),
    sa.Column('units_inspected', sa.Integer(), nullable=True),
    sa.Column('mom_received_date', sa.Date(), nullable=True),
    sa.Column('dispatch_clearance_date', sa.Date(), nullable=True),
    sa.Column('dispatch_clearance_delay', sa.Integer(), nullable=True),
    sa.Column('asn_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_note_no', sa.String(length=100), nullable=True),
    sa.Column('delivered_quantity', sa.Integer(), nullable=True),
    sa.Column('pending_lot_id', sa.String(length=20), nullable=True),
    sa.Column('goods_receipt_no', sa.String(length=100), nullable=True),
    sa.Column('delivery_delay_days', sa.Integer(), nullable=True),
    sa.Column('delay_by_dewa', sa.Integer(), nullable=True),
    sa.Column('other_delay_by_dewa', sa.Integer(), nullable=True),
    sa.Column('total_ld_delay', sa.Integer(), nullable=True),
    sa.Column('invoice_nos', sa.String(length=200), nullable=True),
    sa.Column('invoice_dates', sa.String(length=200), nullable=True),
    sa.Column('invoice_values', sa.String(length=200), nullable=True),
    sa.Column('srm_invoice_no', sa.String(length=100), nullable=True),
    sa.Column('contractual_payment_date', sa.Date(), nullable=True),
    sa.Column('payment_amount_received', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payment_received_date', sa.Date(), nullable=True),
    sa.Column('commission_calculated', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('commission_invoice_no', sa.String(length=100), nullable=True),
    sa.Column('commission_invoice_date', sa.Date(), nullable=True),
    sa.Column('commission_received_date', sa.Date(), nullable=True),
    sa.Column('shipment_arrival_notice', sa.Date(), nullable=True),
    sa.Column('shipment_arrival_actual', sa.Date(), nullable=True),
    sa.Column('delivery_auth_application', sa.Date(), nullable=True),
    sa.Column('delay_in_authorisation_days', sa.Integer(), nullable=True),
    sa.Column('gatepass_date', sa.Date(), nullable=True),
    sa.Column('payment_application_date', sa.Date(), nullable=True),
    sa.Column('revised_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['order_item_detail_id'], ['order_item_details.order_item_detail_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lot_id')
    )
    op.create_index(op.f('ix_lot_monitoring_lot_id'), 'lot_monitoring', ['lot_id'], unique=False)
    op.create_index(op.f('ix_lot_monitoring_order_item_detail_id'), 'lot_monitoring', ['order_item_detail_id'], unique=False)
    op.create_table('delivery_procedures',
    sa.Column('dp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.String(length=20), nullable=False),
    sa.Column('order_item_detail_id', sa.Integer(), nullable=False),
    sa.Column('shipment_etd', sa.Date(), nullable=True),
    sa.Column('shipment_eta', sa.Date(), nullable=True),
    sa.Column('receive_shipping_docs_status', sa.Enum('ALL_RECEIVED', 'PARTIAL_RECEIVED', name='doc_receive_status_enum'), nullable=True),
    sa.Column('receive_shipping_docs_date', sa.Date(), nullable=True),
    sa.Column('delivery_approval_date', sa.Date(), nullable=True),
    sa.Column('customs_exemption_date', sa.Date(), nullable=True),
    sa.Column('cd_to_clearing_agent_date', sa.Date(), nullable=True),
    sa.Column('asn_no', sa.String(length=100), nullable=True),
    sa.Column('asn_date', sa.Date(), nullable=True),
    sa.Column('delivery_email_date', sa.Date(), nullable=True),
    sa.Column('delivery_note_no', sa.String(length=100), nullable=True),
    sa.Column('dn_date', sa.Date(), nullable=True),
    sa.Column('gate_pass_creation_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lot_monitoring.lot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_detail_id'], ['order_item_details.order_item_detail_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dp_id')
    )
    op.create_index(op.f('ix_delivery_procedures_dp_id'), 'delivery_procedures', ['dp_id'], unique=False)
    op.create_index(op.f('ix_delivery_procedures_lot_id'), 'delivery_procedures', ['lot_id'], unique=False)
    op.create_index(op.f('ix_delivery_procedures_order_item_detail_id'), 'delivery_procedures', ['order_item_detail_id'], unique=False)
    op.create_table('discrepancies',
    sa.Column('discrepancy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.String(length=20), nullable=False),
    sa.Column('dewa_letter_ref', sa.String(length=100), nullable=False),
    sa.Column('letter_date', sa.Date(), nullable=False),
    sa.Column('pending_quantity', sa.Integer(), nullable=True),
    sa.Column('unit_sl_nos', sa.String(length=200), nullable=True),
    sa.Column('discrepancies', sa.Text(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('pending_status', sa.Boolean(), nullable=False),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('delivery_note_no', sa.String(length=100), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lot_monitoring.lot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discrepancy_id')
    )
    op.create_index(op.f('ix_discrepancies_discrepancy_id'), 'discrepancies', ['discrepancy_id'], unique=False)
    op.create_index(op.f('ix_discrepancies_lot_id'), 'discrepancies', ['lot_id'], unique=False)
    op.create_table('liquidated_damages',
    sa.Column('ld_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.String(length=20), nullable=False),
    sa.Column('lot_qty', sa.Integer(), nullable=False),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('quantities_delivered', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('delivery_delays_days', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lot_monitoring.lot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ld_id')
    )
    op.create_index(op.f('ix_liquidated_damages_ld_id'), 'liquidated_damages', ['ld_id'], unique=False)
    op.create_index(op.f('ix_liquidated_damages_lot_id'), 'liquidated_damages', ['lot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liquidated_damages_lot_id'), table_name='liquidated_damages')
    op.drop_index(op.f('ix_liquidated_damages_ld_id'), table_name='liquidated_damages')
    op.drop_table('liquidated_damages')
    op.drop_index(op.f('ix_discrepancies_lot_id'), table_name='discrepancies')
    op.drop_index(op.f('ix_discrepancies_discrepancy_id'), table_name='discrepancies')
    op.drop_table('discrepancies')
    op.drop_index(op.f('ix_delivery_procedures_order_item_detail_id'), table_name='delivery_procedures')
    op.drop_index(op.f('ix_delivery_procedures_lot_id'), table_name='delivery_procedures')
    op.drop_index(op.f('ix_delivery_procedures_dp_id'), table_name='delivery_procedures')
    op.drop_table('delivery_procedures')
    op.drop_index(op.f('ix_lot_monitoring_order_item_detail_id'), table_name='lot_monitoring')
    op.drop_index(op.f('ix_lot_monitoring_lot_id'), table_name='lot_monitoring')
    op.drop_table('lot_monitoring')
    op.drop_index(op.f('ix_order_item_details_order_item_detail_id'), table_name='order_item_details')
    op.drop_index(op.f('ix_order_item_details_order_id'), table_name='order_item_details')
    op.drop_index(op.f('ix_order_item_details_item_id'), table_name='order_item_details')
    op.drop_table('order_item_details')
    op.drop_index(op.f('ix_tender_company_items_tendering_companies_id'), table_name='tender_company_items')
    op.drop_index(op.f('ix_tender_company_items_item_no_dewa'), table_name='tender_company_items')
    op.drop_index(op.f('ix_tender_company_items_id'), table_name='tender_company_items')
    op.drop_table('tender_company_items')
    op.drop_index(op.f('ix_pre_tender_clarifications_tendering_companies_id'), table_name='pre_tender_clarifications')
    op.drop_index(op.f('ix_pre_tender_clarifications_pre_ptc_id'), table_name='pre_tender_clarifications')
    op.drop_table('pre_tender_clarifications')
    op.drop_index(op.f('ix_post_tender_clarifications_tendering_companies_id'), table_name='post_tender_clarifications')
    op.drop_index(op.f('ix_post_tender_clarifications_ptc_id'), table_name='post_tender_clarifications')
    op.drop_table('post_tender_clarifications')
    op.drop_index(op.f('ix_performance_guarantees_pg_no'), table_name='performance_guarantees')
    op.drop_index(op.f('ix_performance_guarantees_pg_id'), table_name='performance_guarantees')
    op.drop_index(op.f('ix_performance_guarantees_order_id'), table_name='performance_guarantees')
    op.drop_table('performance_guarantees')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_order_event_id'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_event_date'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index(op.f('ix_material_performance_guarantees_order_id'), table_name='material_performance_guarantees')
    op.drop_index(op.f('ix_material_performance_guarantees_mpg_no'), table_name='material_performance_guarantees')
    op.drop_index(op.f('ix_material_performance_guarantees_mpg_id'), table_name='material_performance_guarantees')
    op.drop_table('material_performance_guarantees')
    op.drop_index(op.f('ix_item_master_product_id'), table_name='item_master')
    op.drop_index(op.f('ix_item_master_item_id'), table_name='item_master')
    op.drop_index(op.f('ix_item_master_hs_code'), table_name='item_master')
    op.drop_table('item_master')
    op.drop_index(op.f('ix_tendering_companies_tendering_companies_id'), table_name='tendering_companies')
    op.drop_index(op.f('ix_tendering_companies_tender_no'), table_name='tendering_companies')
    op.drop_index(op.f('ix_tendering_companies_tender_id'), table_name='tendering_companies')
    op.drop_index(op.f('ix_tendering_companies_company_id'), table_name='tendering_companies')
    op.drop_table('tendering_companies')
    op.drop_index(op.f('ix_product_master_product_name'), table_name='product_master')
    op.drop_index(op.f('ix_product_master_product_id'), table_name='product_master')
    op.drop_index(op.f('ix_product_master_company_id'), table_name='product_master')
    op.drop_table('product_master')
    op.drop_index(op.f('ix_order_details_tender_id'), table_name='order_details')
    op.drop_index(op.f('ix_order_details_po_number'), table_name='order_details')
    op.drop_index(op.f('ix_order_details_order_id'), table_name='order_details')
    op.drop_index(op.f('ix_order_details_old_po_id'), table_name='order_details')
    op.drop_index(op.f('ix_order_details_company_id'), table_name='order_details')
    op.drop_table('order_details')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenders_tender_no'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_tender_id'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_events_start_dt'), table_name='events')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_end_dt'), table_name='events')
    op.drop_index(op.f('ix_events_description'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_counter_guarantees_guarantee_ref_number'), table_name='counter_guarantees')
    op.drop_index(op.f('ix_counter_guarantees_cg_id'), table_name='counter_guarantees')
    op.drop_table('counter_guarantees')
    op.drop_index(op.f('ix_company_master_company_name'), table_name='company_master')
    op.drop_index(op.f('ix_company_master_company_id'), table_name='company_master')
    op.drop_table('company_master')
    # ### end Alembic commands ###
