"""default in tendering

Revision ID: a32f7b7fb9ff
Revises: d2e225aefa71
Create Date: 2025-06-30 12:06:30.886485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32f7b7fb9ff'
down_revision: Union[str, Sequence[str], None] = 'd2e225aefa71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenders', 'tender_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('tenders', 'closing_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('tenders', 'tender_fees',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_tenders_tender_no'), table_name='tenders')
    op.create_index(op.f('ix_tenders_tender_no'), 'tenders', ['tender_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenders_tender_no'), table_name='tenders')
    op.create_index(op.f('ix_tenders_tender_no'), 'tenders', ['tender_no'], unique=False)
    op.alter_column('tenders', 'tender_fees',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('tenders', 'closing_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('tenders', 'tender_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
