"""tenders updated

Revision ID: d1b1d074b0ef
Revises: 5d530925010b
Create Date: 2025-06-30 07:44:15.950263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1b1d074b0ef'
down_revision: Union[str, Sequence[str], None] = '5d530925010b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('tender_no', sa.String(length=50), nullable=False))
    op.add_column('tenders', sa.Column('tender_description', sa.Text(), nullable=False))
    op.add_column('tenders', sa.Column('tender_date', sa.Date(), nullable=False))
    op.add_column('tenders', sa.Column('closing_date', sa.Date(), nullable=False))
    op.add_column('tenders', sa.Column('tender_fees', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('tenders', sa.Column('bond_guarantee_amt', sa.Numeric(precision=12, scale=2), nullable=True))
    op.drop_index(op.f('ix_tenders_id'), table_name='tenders')
    op.create_index(op.f('ix_tenders_tender_no'), 'tenders', ['tender_no'], unique=False)
    op.drop_constraint(op.f('tenders_created_by_id_fkey'), 'tenders', type_='foreignkey')
    op.drop_column('tenders', 'created_at')
    op.drop_column('tenders', 'id')
    op.drop_column('tenders', 'description')
    op.drop_column('tenders', 'title')
    op.drop_column('tenders', 'created_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tenders', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('tenders', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tenders', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('tenders', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tenders_created_by_id_fkey'), 'tenders', 'users', ['created_by_id'], ['id'])
    op.drop_index(op.f('ix_tenders_tender_no'), table_name='tenders')
    op.create_index(op.f('ix_tenders_id'), 'tenders', ['id'], unique=False)
    op.drop_column('tenders', 'bond_guarantee_amt')
    op.drop_column('tenders', 'tender_fees')
    op.drop_column('tenders', 'closing_date')
    op.drop_column('tenders', 'tender_date')
    op.drop_column('tenders', 'tender_description')
    op.drop_column('tenders', 'tender_no')
    # ### end Alembic commands ###
